---
#
# install/run heartbeatbeat elk client
#
- name: Install heartbeat rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - heartbeat-elastic
  when: (logging_backend != 'fluentd')

- name: Generate heartbeat configuration template
  template:
    src=heartbeat.yml.j2
    dest=/etc/heartbeat/heartbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  when: (logging_backend != 'fluentd')

- name: Start and enable heartbeat service
  systemd:
    name: heartbeat-elastic
    state: restarted
    enabled: true
  become: true
  when: (logging_backend != 'fluentd')
