---
#
# install/run packetbeat elk client
#
- name: Install packetbeat rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - packetbeat
    - libpcap
  when: (logging_backend != 'fluentd')

- name: Generate packetbeat configuration template
  template:
    src=packetbeat.yml.j2
    dest=/etc/packetbeat/packetbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  when: (logging_backend != 'fluentd')

- name: Start and enable packetbeat service
  systemd:
    name: packetbeat
    state: restarted
    enabled: true
  become: true
  when: (logging_backend != 'fluentd')
