---
#
# install/run filebeat elk client
#
- name: Install filebeat rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - filebeat
  when: (logging_backend != 'fluentd')

- name: Generate filebeat configuration template
  template:
    src=filebeat.yml.j2
    dest=/etc/filebeat/filebeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  when: (logging_backend != 'fluentd')

- name: Start and enable filebeat service
  systemd:
    name: filebeat
    state: restarted
    enabled: true
  become: true
  when: (logging_backend != 'fluentd')

- name: Install rsyslogd for fluentd
  yum: name={{ item }} state=present
  become: true
  with_items:
    - rsyslog
  when: (logging_backend == 'fluentd')

- name: Setup rsyslogd for fluentd
  lineinfile: dest=/etc/rsyslog.conf \
          line="*.* @{{ elk_server }}:{{ fluentd_syslog_port }}"
  when: (logging_backend == 'fluentd')
  register: rsyslog_updated
  become: true

- name: Setup common OpenStack rsyslog logging
  template:
    src=rsyslog-openstack.conf.j2
    dest=/etc/rsyslog.d/openstack-logs.conf
    owner=root
    group=root
    mode=0644
  become: true
  when: (logging_backend == 'fluentd')

- name: Restarting rsyslog for fluentd
  systemd:
    name: rsyslog
    state: restarted
    enabled: true
  ignore_errors: true
  when: (logging_backend == 'fluentd')
  become: true
