
---
#
# install curator tool for managing elasticsearch
#

- name: Copy curator yum repo file
  copy:
    src=curator.repo
    dest=/etc/yum.repos.d/curator.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Import curator GPG Key
  rpm_key: key=http://packages.elastic.co/GPG-KEY-elasticsearch
    state=present
  become: true

- name: Install curator and python-setuptools
  yum: name={{ item }} state=present
  become: true
  with_items:
    - elasticsearch-curator
    - python-setuptools

- name: Create directory for curator files
  file:
    path: /etc/curator
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create directory for curator logs
  file:
    path: /var/log/curator
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Setup curator config
  template:
    src=curator-config.yml.j2
    dest=/etc/curator/curator-config.yml
    owner=root
    group=root
    mode=0644
  become: true

- name: Setup curator template file
  template:
    src=curator-action.yml.j2
    dest=/etc/curator/curator-action.yml
    owner=root
    group=root
    mode=0644
  become: true

# Runs cron job to cleanup indicies every weekday.
- cron:
    name: Curator run
    weekday: '*'
    minute: 0
    hour: 1
    user: root
    job: "/usr/local/bin/curator --config /etc/curator/curator-config.yml /etc/curator/curator-action.yml >> /var/log/curator/curator_cleanup.log 2>&1"
    cron_file: curator-daily-cleanup
  become: true
