---
#
# Install/run elasticsearch
#

- name: Install libsemanage-python and dependencies
  yum: name={{ item }} state=present
  become: true
  with_items:
    - libsemanage-python

- name: Copy elasticsearch yum repo file
  copy:
    src=elastic.repo
    dest=/etc/yum.repos.d/elastic.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install elasticsearch and openjdk
  yum: name={{ item }} state=present
  become: true
  with_items:
    - elasticsearch
    - java-1.8.0-openjdk

- name: Copy templated elasticsearch.yml
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=elasticsearch
    mode=0660
  become: true
  ignore_errors: true

- name: Check if system memory is greater than 64G
  debug: msg="System memory is {{ansible_memory_mb.real.total | int}} so setting heapsize to 32G upper limit"
  when: ansible_memory_mb.real.total|int >= 65536
  become: true

- name: Apply heapsize start tuning for systems with greater than 64G memory
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xms2g'
    line='-Xms31g'
  when: ansible_memory_mb.real.total|int >= 65536
  become: true

- name: Apply heapsize end tuning for systems with greater than 64G memory
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xmx2g'
    line='-Xmx31g'
  when: ansible_memory_mb.real.total|int >= 65536
  register: elasticsearch_updated
  become: true

- name: Print extended documentation for heapsize tuning
  debug: msg="Refer to https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html"
  when: ansible_memory_mb.real.total|int >= 65536
  become: true

- name: Update elasticsearch startup with start heap size
  become: true
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xms2g'
    line='-Xms{{ (ansible_memory_mb.real.total / 2) | int }}m'
  when: ansible_memory_mb.real.total|int < 65536

- name: Update elasticsearch startup with end heap size
  become: true
  lineinfile:
    path=/etc/elasticsearch/jvm.options
    regexp='^-Xmx2g'
    line='-Xmx{{ (ansible_memory_mb.real.total / 2) | int }}m'
  when: ansible_memory_mb.real.total|int < 65536
  register: elasticsearch_updated

- name: Start and enable elasticsearch service
  systemd:
    name: elasticsearch
    state: restarted
    enabled: true
  become: true

- name: Create the default template without replication of shards
  command: curl -XPUT 'localhost:9200/_template/default?pretty' -H 'Content-Type: application/json' -d '{"index_patterns": ["*"],"order" : 0,"settings": {"number_of_shards": 1,"number_of_replicas": 0}}'
  become: true
