---
#
# install/run packetbeat elk client
#
- name: Install metricbeat rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - metricbeat
  when: (logging_backend != 'fluentd')

- name: Generate metricbeat configuration template
  template:
    src=metricbeat.yml.j2
    dest=/etc/metricbeat/metricbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  when: (logging_backend != 'fluentd')

- name: Start and enable metricbeat service
  systemd:
    name: metricbeat
    state: restarted
    enabled: true
  become: true
  when: (logging_backend != 'fluentd')
